modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/dries007/TapeMouse/issues"
license="BSD-3-Clause license"
[[mods]]
modId="tapemouse"
version="${file.jarVersion}"
displayName="TapeMouse"
updateJSONURL="https://mc.dries007.net/TapeMouse.json"
displayURL="https://github.com/dries007/TapeMouse"
logoFile="logo.png"
credits=""
authors="Dries007"
description='''
Tape + Mouse = TapeMouse
'''
